model_name: mistralai/Mixtral-8x7B-v0.1
use_bf16: true
completion_only_loss: true
model:
  trust_remote_code: true
  attn_implementation: flash_attention_2
bnb_config:
  load_in_8bit: true
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: true
lora_config:
  r: 64
  lora_alpha: 32
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - w1
    - w2
    - w3
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM
tokenizer:
  use_fast: true
  trust_remote_code: true
  padding_side: right
  seq_max_length: 2048
example_template: |
  <|user|>
  {prompt}
  <|assistant|>
  {response}
completion_template: |
  <|assistant|>