model_name: Qwen/Qwen1.5-14B
use_bf16: true
completion_only_loss: true
model:
  trust_remote_code: true
  attn_implementation: flash_attention_2
bnb_config:
  load_in_8bit: true
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: true
lora_config:
  r: 64
  lora_alpha: 32
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM
tokenizer:
  use_fast: true
  trust_remote_code: true
  padding_side: right
  seq_max_length: 2048
example_template: |
  <|im_start|>system
  You are a helpful assistant.<|im_end|>
  <|im_start|>user
  {prompt}<|im_end|>
  <|im_start|>assistant
  {response}<|im_end|>
completion_template: |
  <|im_start|>assistant